package unbounded_stream_collect

import (
	"testing"

	"github.com/andrueandersoncs/better-typescript/internal/analysis"
	"github.com/andrueandersoncs/better-typescript/internal/ruletest"
)

func TestRule(t *testing.T) {
	ruletest.Assert(t, "testdata", UnboundedStreamCollectRule, []analysis.Violation{
		{RuleName: "unbounded-stream-collect", Level: "error", Message: "Avoid collecting a Stream without a locally established bound. Use a finite source or apply Stream.take with a nonnegative finite numeric literal before runCollect, collect, or Sink.collect. Incremental consumers such as runForEach and runDrain do not retain every element.", FilePath: "violation.ts", Line: 8, Column: 1},
		{RuleName: "unbounded-stream-collect", Level: "error", Message: "Avoid collecting a Stream without a locally established bound. Use a finite source or apply Stream.take with a nonnegative finite numeric literal before runCollect, collect, or Sink.collect. Incremental consumers such as runForEach and runDrain do not retain every element.", FilePath: "violation.ts", Line: 9, Column: 13},
		{RuleName: "unbounded-stream-collect", Level: "error", Message: "Avoid collecting a Stream without a locally established bound. Use a finite source or apply Stream.take with a nonnegative finite numeric literal before runCollect, collect, or Sink.collect. Incremental consumers such as runForEach and runDrain do not retain every element.", FilePath: "violation.ts", Line: 10, Column: 1},
		{RuleName: "unbounded-stream-collect", Level: "error", Message: "Avoid collecting a Stream without a locally established bound. Use a finite source or apply Stream.take with a nonnegative finite numeric literal before runCollect, collect, or Sink.collect. Incremental consumers such as runForEach and runDrain do not retain every element.", FilePath: "violation.ts", Line: 11, Column: 13},
		{RuleName: "unbounded-stream-collect", Level: "error", Message: "Avoid collecting a Stream without a locally established bound. Use a finite source or apply Stream.take with a nonnegative finite numeric literal before runCollect, collect, or Sink.collect. Incremental consumers such as runForEach and runDrain do not retain every element.", FilePath: "violation.ts", Line: 12, Column: 13},
		{RuleName: "unbounded-stream-collect", Level: "error", Message: "Avoid collecting a Stream without a locally established bound. Use a finite source or apply Stream.take with a nonnegative finite numeric literal before runCollect, collect, or Sink.collect. Incremental consumers such as runForEach and runDrain do not retain every element.", FilePath: "violation.ts", Line: 13, Column: 1},
		{RuleName: "unbounded-stream-collect", Level: "error", Message: "Avoid collecting a Stream without a locally established bound. Use a finite source or apply Stream.take with a nonnegative finite numeric literal before runCollect, collect, or Sink.collect. Incremental consumers such as runForEach and runDrain do not retain every element.", FilePath: "violation.ts", Line: 14, Column: 1},
		{RuleName: "unbounded-stream-collect", Level: "error", Message: "Avoid collecting a Stream without a locally established bound. Use a finite source or apply Stream.take with a nonnegative finite numeric literal before runCollect, collect, or Sink.collect. Incremental consumers such as runForEach and runDrain do not retain every element.", FilePath: "violation.ts", Line: 15, Column: 13},
		{RuleName: "unbounded-stream-collect", Level: "error", Message: "Avoid collecting a Stream without a locally established bound. Use a finite source or apply Stream.take with a nonnegative finite numeric literal before runCollect, collect, or Sink.collect. Incremental consumers such as runForEach and runDrain do not retain every element.", FilePath: "violation.ts", Line: 15, Column: 59},
		{RuleName: "unbounded-stream-collect", Level: "error", Message: "Avoid collecting a Stream without a locally established bound. Use a finite source or apply Stream.take with a nonnegative finite numeric literal before runCollect, collect, or Sink.collect. Incremental consumers such as runForEach and runDrain do not retain every element.", FilePath: "violation.ts", Line: 16, Column: 1},
		{RuleName: "unbounded-stream-collect", Level: "error", Message: "Avoid collecting a Stream without a locally established bound. Use a finite source or apply Stream.take with a nonnegative finite numeric literal before runCollect, collect, or Sink.collect. Incremental consumers such as runForEach and runDrain do not retain every element.", FilePath: "violation.ts", Line: 17, Column: 1},
		{RuleName: "unbounded-stream-collect", Level: "error", Message: "Avoid collecting a Stream without a locally established bound. Use a finite source or apply Stream.take with a nonnegative finite numeric literal before runCollect, collect, or Sink.collect. Incremental consumers such as runForEach and runDrain do not retain every element.", FilePath: "violation.ts", Line: 20, Column: 33},
		{RuleName: "unbounded-stream-collect", Level: "error", Message: "Avoid collecting a Stream without a locally established bound. Use a finite source or apply Stream.take with a nonnegative finite numeric literal before runCollect, collect, or Sink.collect. Incremental consumers such as runForEach and runDrain do not retain every element.", FilePath: "violation.ts", Line: 23, Column: 43},
	})
}
