package rules

import (
	"github.com/andrueandersoncs/better-typescript/internal/rules/boundary_schema_decode"
	"github.com/andrueandersoncs/better-typescript/internal/rules/bounded_retry_schedule"
	"github.com/andrueandersoncs/better-typescript/internal/rules/cache_per_request"
	"github.com/andrueandersoncs/better-typescript/internal/rules/cache_preference"
	"github.com/andrueandersoncs/better-typescript/internal/rules/closed_abstraction"
	"github.com/andrueandersoncs/better-typescript/internal/rules/config_refined_values"
	"github.com/andrueandersoncs/better-typescript/internal/rules/dependent_layer_merge"
	"github.com/andrueandersoncs/better-typescript/internal/rules/duplicate_shape"
	"github.com/andrueandersoncs/better-typescript/internal/rules/effect_fn_name"
	"github.com/andrueandersoncs/better-typescript/internal/rules/effect_test_style"
	"github.com/andrueandersoncs/better-typescript/internal/rules/function_derived_model"
	"github.com/andrueandersoncs/better-typescript/internal/rules/global_config_mutation"
	"github.com/andrueandersoncs/better-typescript/internal/rules/handrolled_ttl_cache"
	"github.com/andrueandersoncs/better-typescript/internal/rules/http_client_preference"
	"github.com/andrueandersoncs/better-typescript/internal/rules/http_response_validation"
	"github.com/andrueandersoncs/better-typescript/internal/rules/http_status_decode_order"
	"github.com/andrueandersoncs/better-typescript/internal/rules/idempotent_retry"
	"github.com/andrueandersoncs/better-typescript/internal/rules/inflight_dedupe_map"
	"github.com/andrueandersoncs/better-typescript/internal/rules/layer_forever_acquisition"
	"github.com/andrueandersoncs/better-typescript/internal/rules/missing_rationale"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_async_functions"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_blank_lines_between_single_line_declarations"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_callbacks"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_duplicate_function_names"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_duplicate_if_bodies"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_error_type"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_explicit_any_return"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_first_party_schema_declare"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_for_in_loops"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_for_loops"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_for_of_loops"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_function_keyword"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_immediate_effect_sync"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_inline_boolean_expressions"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_inline_closures"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_instanceof"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_manual_type_dispatch"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_monomorphic_struct_get"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_multiple_boolean_operators"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_mutable_array_methods"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_mutable_variable_declarations"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_mutation"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_nested_calls"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_nested_if_statements"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_new_error"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_non_null_assertion"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_pass_through_object_wrappers"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_property_access_after_call"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_raw_object_types"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_reexports"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_switch_statements"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_throw"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_trivial_effect_fn"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_try_catch"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_undefined"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_unsafe_effect_apis"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_unused"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_value_aliases"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_void_functions"
	"github.com/andrueandersoncs/better-typescript/internal/rules/no_weak_map"
	"github.com/andrueandersoncs/better-typescript/internal/rules/observable_worker_failure"
	"github.com/andrueandersoncs/better-typescript/internal/rules/parameter_bag"
	"github.com/andrueandersoncs/better-typescript/internal/rules/pass_through_conversion"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_composed_callbacks"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_conditional_return"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_context_service_class"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_curried_data_last_functions"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_direct_boolean_return"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_direct_yield"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_effect_array"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_effect_array_append_all"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_effect_array_count_by"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_effect_fn"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_effect_function_constant"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_effect_index_access"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_effect_object"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_effect_property_accessors"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_effect_record_filter_map"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_effect_schema_constructor"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_effect_schema_guard"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_effect_schema_is"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_effect_schema_record"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_effectful_function"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_equivalence_strict_equal"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_eta_reduction"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_function_composition"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_function_flip"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_hash_map"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_hash_set"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_implicit_return"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_inferred_types"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_layer_unwrap"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_option_match"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_pipe_function"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_result_concept_names"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_schema_tagged_struct"
	"github.com/andrueandersoncs/better-typescript/internal/rules/prefer_specific_operation_names"
	"github.com/andrueandersoncs/better-typescript/internal/rules/process_environment"
	"github.com/andrueandersoncs/better-typescript/internal/rules/production_sleep_loops"
	"github.com/andrueandersoncs/better-typescript/internal/rules/raw_fetch_abort_signal"
	"github.com/andrueandersoncs/better-typescript/internal/rules/raw_fetch_outside_adapter"
	"github.com/andrueandersoncs/better-typescript/internal/rules/redundant_alias"
	"github.com/andrueandersoncs/better-typescript/internal/rules/related_kind_files"
	"github.com/andrueandersoncs/better-typescript/internal/rules/require_because_in_comments"
	"github.com/andrueandersoncs/better-typescript/internal/rules/require_blank_lines_around_multiline_declarations"
	"github.com/andrueandersoncs/better-typescript/internal/rules/require_callable_role_name_consistency"
	"github.com/andrueandersoncs/better-typescript/internal/rules/require_command_name_consistency"
	"github.com/andrueandersoncs/better-typescript/internal/rules/require_construction_name_consistency"
	"github.com/andrueandersoncs/better-typescript/internal/rules/require_conversion_direction_consistency"
	"github.com/andrueandersoncs/better-typescript/internal/rules/require_export_jsdoc"
	"github.com/andrueandersoncs/better-typescript/internal/rules/require_lookup_totality_name_consistency"
	"github.com/andrueandersoncs/better-typescript/internal/rules/require_predicate_name_consistency"
	"github.com/andrueandersoncs/better-typescript/internal/rules/require_result_cardinality_name_consistency"
	"github.com/andrueandersoncs/better-typescript/internal/rules/require_result_shape_name_consistency"
	"github.com/andrueandersoncs/better-typescript/internal/rules/retry_without_jitter"
	"github.com/andrueandersoncs/better-typescript/internal/rules/schema_class_models"
	"github.com/andrueandersoncs/better-typescript/internal/rules/schema_error_class"
	"github.com/andrueandersoncs/better-typescript/internal/rules/schema_name_suffix"
	"github.com/andrueandersoncs/better-typescript/internal/rules/schema_optional_key"
	"github.com/andrueandersoncs/better-typescript/internal/rules/schema_record_interface"
	"github.com/andrueandersoncs/better-typescript/internal/rules/scoped_background_work"
	"github.com/andrueandersoncs/better-typescript/internal/rules/scoped_client_cache"
	"github.com/andrueandersoncs/better-typescript/internal/rules/service_method_effect_fn"
	"github.com/andrueandersoncs/better-typescript/internal/rules/speculative_export"
	"github.com/andrueandersoncs/better-typescript/internal/rules/stream_pagination"
	"github.com/andrueandersoncs/better-typescript/internal/rules/test_clock_for_time"
	"github.com/andrueandersoncs/better-typescript/internal/rules/test_sleeps"
	"github.com/andrueandersoncs/better-typescript/internal/rules/typed_boundary_error"
	"github.com/andrueandersoncs/better-typescript/internal/rules/typed_error_recovery"
	"github.com/andrueandersoncs/better-typescript/internal/rules/typescript_namespaces"
	"github.com/andrueandersoncs/better-typescript/internal/rules/unbounded_stream_buffer"
	"github.com/andrueandersoncs/better-typescript/internal/rules/unbounded_stream_collect"
	"github.com/andrueandersoncs/better-typescript/internal/rules/unsafe_casts"
	"github.com/andrueandersoncs/better-typescript/internal/rules/unused_field"

	"github.com/andrueandersoncs/better-typescript/internal/rule"
)

var BuiltinRules = []rule.Rule{
	boundary_schema_decode.Rule,
	bounded_retry_schedule.Rule,
	cache_per_request.Rule,
	cache_preference.Rule,
	closed_abstraction.Rule,
	config_refined_values.Rule,
	dependent_layer_merge.Rule,
	duplicate_shape.Rule,
	effect_fn_name.Rule,
	effect_test_style.Rule,
	function_derived_model.Rule,
	global_config_mutation.Rule,
	handrolled_ttl_cache.Rule,
	http_client_preference.Rule,
	http_response_validation.Rule,
	http_status_decode_order.Rule,
	idempotent_retry.IdempotentRetryRule,
	inflight_dedupe_map.InflightDedupeMapRule,
	layer_forever_acquisition.LayerForeverAcquisitionRule,
	missing_rationale.MissingRationaleRule,
	no_async_functions.NoAsyncFunctionsRule,
	no_blank_lines_between_single_line_declarations.NoBlankLinesBetweenSingleLineDeclarationsRule,
	no_callbacks.NoCallbacksRule,
	no_duplicate_function_names.NoDuplicateFunctionNamesRule,
	no_duplicate_if_bodies.NoDuplicateIfBodiesRule,
	no_error_type.NoErrorTypeRule,
	no_explicit_any_return.NoExplicitAnyReturnRule,
	no_first_party_schema_declare.NoFirstPartySchemaDeclareRule,
	no_for_in_loops.NoForInLoopsRule,
	no_for_loops.NoForLoopsRule,
	no_for_of_loops.NoForOfLoopsRule,
	no_function_keyword.NoFunctionKeywordRule,
	no_immediate_effect_sync.Rule,
	no_inline_boolean_expressions.Rule,
	no_inline_closures.Rule,
	no_instanceof.Rule,
	no_manual_type_dispatch.Rule,
	no_monomorphic_struct_get.Rule,
	no_multiple_boolean_operators.Rule,
	no_mutable_array_methods.Rule,
	no_mutable_variable_declarations.Rule,
	no_mutation.Rule,
	no_nested_calls.Rule,
	no_nested_if_statements.Rule,
	no_new_error.Rule,
	no_non_null_assertion.Rule,
	no_pass_through_object_wrappers.Rule,
	no_property_access_after_call.Rule,
	no_raw_object_types.Rule,
	no_reexports.Rule,
	no_switch_statements.Rule,
	no_throw.Rule,
	no_trivial_effect_fn.Rule,
	no_try_catch.Rule,
	no_undefined.Rule,
	no_unsafe_effect_apis.Rule,
	no_unused.Rule,
	no_value_aliases.Rule,
	no_void_functions.Rule,
	no_weak_map.Rule,
	observable_worker_failure.Rule,
	parameter_bag.Rule,
	pass_through_conversion.Rule,
	prefer_composed_callbacks.Rule,
	prefer_conditional_return.Rule,
	prefer_context_service_class.Rule,
	prefer_curried_data_last_functions.Rule,
	prefer_direct_boolean_return.Rule,
	prefer_direct_yield.Rule,
	prefer_effect_array.Rule,
	prefer_effect_array_append_all.Rule,
	prefer_effect_array_count_by.Rule,
	prefer_effect_fn.Rule,
	prefer_effect_function_constant.Rule,
	prefer_effect_index_access.Rule,
	prefer_effect_object.Rule,
	prefer_effect_property_accessors.Rule,
	prefer_effect_record_filter_map.Rule,
	prefer_effect_schema_constructor.Rule,
	prefer_effect_schema_guard.Rule,
	prefer_effect_schema_is.Rule,
	prefer_effect_schema_record.Rule,
	prefer_effectful_function.PreferEffectfulFunctionRule,
	prefer_equivalence_strict_equal.PreferEquivalenceStrictEqualRule,
	prefer_eta_reduction.PreferEtaReductionRule,
	prefer_function_composition.PreferFunctionCompositionRule,
	prefer_function_flip.PreferFunctionFlipRule,
	prefer_hash_map.PreferHashMapRule,
	prefer_hash_set.PreferHashSetRule,
	prefer_implicit_return.PreferImplicitReturnRule,
	prefer_inferred_types.PreferInferredTypesRule,
	prefer_layer_unwrap.PreferLayerUnwrapRule,
	prefer_option_match.PreferOptionMatchRule,
	prefer_pipe_function.PreferPipeFunctionRule,
	prefer_result_concept_names.PreferResultConceptNamesRule,
	prefer_schema_tagged_struct.PreferSchemaTaggedStructRule,
	prefer_specific_operation_names.PreferSpecificOperationNamesRule,
	process_environment.ProcessEnvironmentRule,
	production_sleep_loops.Rule,
	raw_fetch_abort_signal.Rule,
	raw_fetch_outside_adapter.Rule,
	redundant_alias.Rule,
	related_kind_files.Rule,
	require_because_in_comments.Rule,
	require_blank_lines_around_multiline_declarations.Rule,
	require_callable_role_name_consistency.Rule,
	require_command_name_consistency.Rule,
	require_construction_name_consistency.Rule,
	require_conversion_direction_consistency.Rule,
	require_export_jsdoc.Rule,
	require_lookup_totality_name_consistency.Rule,
	require_predicate_name_consistency.Rule,
	require_result_cardinality_name_consistency.Rule,
	require_result_shape_name_consistency.Rule,
	retry_without_jitter.Rule,
	schema_class_models.Rule,
	schema_error_class.SchemaErrorClassRule,
	schema_name_suffix.Rule,
	schema_optional_key.SchemaOptionalKeyRule,
	schema_record_interface.SchemaRecordInterfaceRule,
	scoped_background_work.ScopedBackgroundWorkRule,
	scoped_client_cache.ScopedClientCacheRule,
	service_method_effect_fn.ServiceMethodEffectFnRule,
	speculative_export.SpeculativeExportRule,
	stream_pagination.StreamPaginationRule,
	test_clock_for_time.TestClockForTimeRule,
	test_sleeps.TestSleepsRule,
	typed_boundary_error.TypedBoundaryErrorRule,
	typed_error_recovery.TypedErrorRecoveryRule,
	typescript_namespaces.TypescriptNamespacesRule,
	unbounded_stream_buffer.UnboundedStreamBufferRule,
	unbounded_stream_collect.UnboundedStreamCollectRule,
	unsafe_casts.UnsafeCastsRule,
	unused_field.UnusedFieldRule,
}
