package no_first_party_root_class

import (
	"testing"

	"github.com/andrueandersoncs/better-typescript/internal/analysis"
	"github.com/andrueandersoncs/better-typescript/internal/ruletest"
)

func TestRule(t *testing.T) {
	ruletest.Assert(t, "testdata/project", Rule, []analysis.Violation{
		{RuleName: "no-first-party-root-class", Level: "error", Message: "Avoid unsupported first-party class declarations. Use a class only when it extends another class without private methods, or when it contains one private constructor and only public static methods. Replace other classes with factory functions and structural data.", FilePath: "src/cases.ts", Line: 2, Column: 14},
		{RuleName: "no-first-party-root-class", Level: "error", Message: "Avoid unsupported first-party class declarations. Use a class only when it extends another class without private methods, or when it contains one private constructor and only public static methods. Replace other classes with factory functions and structural data.", FilePath: "src/cases.ts", Line: 9, Column: 14},
		{RuleName: "no-first-party-root-class", Level: "error", Message: "Avoid unsupported first-party class declarations. Use a class only when it extends another class without private methods, or when it contains one private constructor and only public static methods. Replace other classes with factory functions and structural data.", FilePath: "src/cases.ts", Line: 10, Column: 14},
		{RuleName: "no-first-party-root-class", Level: "error", Message: "Avoid unsupported first-party class declarations. Use a class only when it extends another class without private methods, or when it contains one private constructor and only public static methods. Replace other classes with factory functions and structural data.", FilePath: "src/cases.ts", Line: 11, Column: 14},
		{RuleName: "no-first-party-root-class", Level: "error", Message: "Avoid unsupported first-party class declarations. Use a class only when it extends another class without private methods, or when it contains one private constructor and only public static methods. Replace other classes with factory functions and structural data.", FilePath: "src/cases.ts", Line: 14, Column: 14},
		{RuleName: "no-first-party-root-class", Level: "error", Message: "Avoid unsupported first-party class declarations. Use a class only when it extends another class without private methods, or when it contains one private constructor and only public static methods. Replace other classes with factory functions and structural data.", FilePath: "src/cases.ts", Line: 17, Column: 14},
		{RuleName: "no-first-party-root-class", Level: "error", Message: "Avoid unsupported first-party class declarations. Use a class only when it extends another class without private methods, or when it contains one private constructor and only public static methods. Replace other classes with factory functions and structural data.", FilePath: "src/cases.ts", Line: 21, Column: 14},
		{RuleName: "no-first-party-root-class", Level: "error", Message: "Avoid unsupported first-party class declarations. Use a class only when it extends another class without private methods, or when it contains one private constructor and only public static methods. Replace other classes with factory functions and structural data.", FilePath: "src/cases.ts", Line: 25, Column: 14},
		{RuleName: "no-first-party-root-class", Level: "error", Message: "Avoid unsupported first-party class declarations. Use a class only when it extends another class without private methods, or when it contains one private constructor and only public static methods. Replace other classes with factory functions and structural data.", FilePath: "src/cases.ts", Line: 30, Column: 14},
		{RuleName: "no-first-party-root-class", Level: "error", Message: "Avoid unsupported first-party class declarations. Use a class only when it extends another class without private methods, or when it contains one private constructor and only public static methods. Replace other classes with factory functions and structural data.", FilePath: "src/cases.ts", Line: 35, Column: 14},
		{RuleName: "no-first-party-root-class", Level: "error", Message: "Avoid unsupported first-party class declarations. Use a class only when it extends another class without private methods, or when it contains one private constructor and only public static methods. Replace other classes with factory functions and structural data.", FilePath: "src/cases.ts", Line: 39, Column: 14},
		{RuleName: "no-first-party-root-class", Level: "error", Message: "Avoid unsupported first-party class declarations. Use a class only when it extends another class without private methods, or when it contains one private constructor and only public static methods. Replace other classes with factory functions and structural data.", FilePath: "src/cases.ts", Line: 43, Column: 14},
		{RuleName: "no-first-party-root-class", Level: "error", Message: "Avoid unsupported first-party class declarations. Use a class only when it extends another class without private methods, or when it contains one private constructor and only public static methods. Replace other classes with factory functions and structural data.", FilePath: "src/cases.ts", Line: 46, Column: 14},
		{RuleName: "no-first-party-root-class", Level: "error", Message: "Avoid unsupported first-party class declarations. Use a class only when it extends another class without private methods, or when it contains one private constructor and only public static methods. Replace other classes with factory functions and structural data.", FilePath: "src/cases.ts", Line: 49, Column: 14},
	})
}
