// EffectQualityRuleKind is kind vocabulary because detectors and reports must share literals.
export type EffectQualityRuleKind =
  | "unsafe-casts"
  | "schema-class-models"
  | "typescript-namespaces"
  | "process-environment"
  | "test-sleeps"
  | "production-sleep-loops"
  | "unbounded-stream-collect"
  | "unbounded-stream-buffer"
  | "handrolled-ttl-cache"
  | "inflight-dedupe-map"
  | "cache-per-request"
  | "scoped-client-cache"
  | "raw-fetch-abort-signal"
  | "typed-error-recovery"
  | "layer-forever-acquisition"
  | "global-config-mutation"
  | "service-method-effect-fn"
  | "effect-fn-name"
  | "schema-record-interface"
  | "schema-optional-key"
  | "schema-error-class"
  | "config-secret-redaction"
  | "bounded-retry-schedule"
  | "http-response-validation"
  | "http-status-decode-order"
  | "effect-test-style"
