// EffectQualityAdviceKind is kind vocabulary because evidence and advice must share kind keys.
export type EffectQualityAdviceKind =
  | "config-refined-values"
  | "retry-without-jitter"
  | "raw-fetch-outside-adapter"
  | "test-live-runtime"
  | "test-clock-for-time"
  | "thin-http-handlers"
  | "transaction-network-work"
  | "layer-authority-visibility"
  | "layer-composition"
  | "scoped-background-work"
  | "cache-preference"
  | "stream-pagination"
  | "public-queue"
  | "keyed-stream-work"
  | "typed-boundary-error"
  | "boundary-schema-decode"
  | "idempotent-retry"
  | "observable-worker-failure"
  | "http-client-preference"
