package no_module_mocking

import (
	"testing"

	"github.com/andrueandersoncs/better-typescript/internal/analysis"
	"github.com/andrueandersoncs/better-typescript/internal/ruletest"
)

func TestRule(t *testing.T) {
	ruletest.Assert(t, "testdata", Rule, []analysis.Violation{
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "aliased.ts", Line: 3, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "aliased.ts", Line: 5, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "bunMock.ts", Line: 2, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "bunMock.ts", Line: 4, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "cases.ts", Line: 1, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "helperNamespace.ts", Line: 2, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "helperNamespace.ts", Line: 7, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "imported.ts", Line: 2, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "jestApis.ts", Line: 2, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "jestApis.ts", Line: 3, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "namespaced.ts", Line: 2, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "namespaced.ts", Line: 3, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "namespaced.ts", Line: 5, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "nodeContext.ts", Line: 3, Column: 3},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "nodeContext.ts", Line: 5, Column: 47},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "reexported.ts", Line: 2, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "reexported.ts", Line: 3, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "replacers.ts", Line: 2, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "replacers.ts", Line: 4, Column: 17},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "replacers.ts", Line: 5, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "replacers.ts", Line: 6, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "spyOn.ts", Line: 3, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "spyOn.ts", Line: 5, Column: 1},
		{RuleName: "no-module-mocking", Level: "error", Message: "Replace module mocking with dependency injection through a real interface, service layer, or faithful test implementation. Exercise the production dependency seam instead of replacing a module namespace.", FilePath: "unstable.ts", Line: 2, Column: 1},
	})
}
