package prefer_effect_schema_constructor

import (
	"testing"

	"github.com/andrueandersoncs/better-typescript/internal/analysis"
	"github.com/andrueandersoncs/better-typescript/internal/ruletest"
)

func TestRule(t *testing.T) {
	ruletest.Assert(t, "testdata", Rule, []analysis.Violation{
		{RuleName: "prefer-effect-schema-constructor", Level: "error", Message: "Avoid constructing an Effect Schema class with new. Call the same class's static make method instead: SomeSchema.make(...).", FilePath: "schema-class-violation.ts", Line: 5, Column: 19},
		{RuleName: "prefer-effect-schema-constructor", Level: "error", Message: "Avoid declaring or returning a raw \"User\" object literal. Reuse the existing Effect Schema for the \"User\" protocol variant and construct it through schema.make. If no such model exists, first decide whether this tagged value is an independent protocol concept or this function is only a procedural seam. Model a reusable boundary-crossing variant with Schema.TaggedStruct and a Schema-suffixed const and a decoded interface named without the suffix; use Schema.TaggedUnion for boundary-crossing unions. Use Data.TaggedEnum for internal workflow decisions or state, and Schema.TaggedErrorClass only for typed errors.", FilePath: "violation.ts", Line: 2, Column: 10},
		{RuleName: "prefer-effect-schema-constructor", Level: "error", Message: "Avoid declaring or returning a raw \"Quoted\" object literal. Reuse the existing Effect Schema for the \"Quoted\" protocol variant and construct it through schema.make. If no such model exists, first decide whether this tagged value is an independent protocol concept or this function is only a procedural seam. Model a reusable boundary-crossing variant with Schema.TaggedStruct and a Schema-suffixed const and a decoded interface named without the suffix; use Schema.TaggedUnion for boundary-crossing unions. Use Data.TaggedEnum for internal workflow decisions or state, and Schema.TaggedErrorClass only for typed errors.", FilePath: "violation.ts", Line: 6, Column: 10},
		{RuleName: "prefer-effect-schema-constructor", Level: "error", Message: "Avoid declaring or returning a raw \"Computed\" object literal. Reuse the existing Effect Schema for the \"Computed\" protocol variant and construct it through schema.make. If no such model exists, first decide whether this tagged value is an independent protocol concept or this function is only a procedural seam. Model a reusable boundary-crossing variant with Schema.TaggedStruct and a Schema-suffixed const and a decoded interface named without the suffix; use Schema.TaggedUnion for boundary-crossing unions. Use Data.TaggedEnum for internal workflow decisions or state, and Schema.TaggedErrorClass only for typed errors.", FilePath: "violation.ts", Line: 10, Column: 10},
		{RuleName: "prefer-effect-schema-constructor", Level: "error", Message: "Avoid declaring or returning a raw \"\" object literal. Reuse the existing Effect Schema for the \"\" protocol variant and construct it through schema.make. If no such model exists, first decide whether this tagged value is an independent protocol concept or this function is only a procedural seam. Model a reusable boundary-crossing variant with Schema.TaggedStruct and a Schema-suffixed const and a decoded interface named without the suffix; use Schema.TaggedUnion for boundary-crossing unions. Use Data.TaggedEnum for internal workflow decisions or state, and Schema.TaggedErrorClass only for typed errors.", FilePath: "violation.ts", Line: 14, Column: 10},
		{RuleName: "prefer-effect-schema-constructor", Level: "error", Message: "Avoid declaring or returning a raw \"Selected\" object literal. Reuse the existing Effect Schema for the \"Selected\" protocol variant and construct it through schema.make. If no such model exists, first decide whether this tagged value is an independent protocol concept or this function is only a procedural seam. Model a reusable boundary-crossing variant with Schema.TaggedStruct and a Schema-suffixed const and a decoded interface named without the suffix; use Schema.TaggedUnion for boundary-crossing unions. Use Data.TaggedEnum for internal workflow decisions or state, and Schema.TaggedErrorClass only for typed errors.", FilePath: "violation.ts", Line: 18, Column: 17},
	})
}
